spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eteration-banking
    username: postgres
    password: 12345
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080